implementation("com.google.accompanist:accompanist-systemuicontroller:0.31.0-alpha")
    implementation ("com.google.accompanist:accompanist-permissions:0.23.1")
//    implementation ("com.google.accompanist:accompanist-permissions:0.30.1")
    runtimeOnly("androidx.compose.foundation:foundation:1.6.2")
    implementation("com.google.code.gson:gson:2.10.1")
    implementation("androidx.navigation:navigation-runtime-ktx:2.7.7")
    implementation("androidx.navigation:navigation-compose:2.7.7")
    implementation ("androidx.lifecycle:lifecycle-runtime-compose:2.6.2")
    implementation("androidx.core:core-splashscreen:1.0.1")